import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'fs';
import path from 'path';
import { runTradeMigration } from './migrate-trade-audit-fields.ts';

describe('migrate-trade-audit-fields', () => {
  const tempDbPath = path.join(process.cwd(), 'temp_test_db_migration.json');

  const sampleDb = {
    trades: [
      { id: 'trade_1', pnl: 50, mode: 'PAPER', timestamp: 100000 },
      { id: 'hist_trade_99', pnl: 10, mode: 'PAPER', timestamp: 100000 }
    ],
    tradeHistory: [
      { id: 'trade_2', pnl: -20, closeReason: 'принудительно закрыта при смене виртуального баланса', timestamp: 100000 }
    ]
  };

  beforeEach(() => {
    fs.writeFileSync(tempDbPath, JSON.stringify(sampleDb, null, 2));
  });

  afterEach(() => {
    if (fs.existsSync(tempDbPath)) fs.unlinkSync(tempDbPath);
    // Cleanup any backup files generated by test
    const files = fs.readdirSync(process.cwd());
    for (const f of files) {
      if (f.startsWith('temp_test_db_migration.json.backup_')) {
        fs.unlinkSync(path.join(process.cwd(), f));
      }
    }
  });

  it('runs dry-run without mutating database file', () => {
    const res = runTradeMigration({ dbPath: tempDbPath, apply: false });
    expect(res.success).toBe(true);
    expect(res.dryRun).toBe(true);

    const fileContent = JSON.parse(fs.readFileSync(tempDbPath, 'utf-8'));
    expect(fileContent.trades[0].dataOrigin).toBeUndefined();
  });

  it('applies migration, creates backup, tags fields, and is idempotent', () => {
    // First run with apply
    const res1 = runTradeMigration({ dbPath: tempDbPath, apply: true });
    expect(res1.success).toBe(true);
    expect(res1.migratedTradesCount).toBe(3);

    const fileContent1 = JSON.parse(fs.readFileSync(tempDbPath, 'utf-8'));
    expect(fileContent1.trades[0].dataOrigin).toBe('PAPER');
    expect(fileContent1.trades[1].dataOrigin).toBe('SEED');
    expect(fileContent1.tradeHistory[0].dataOrigin).toBe('FORCED_RESET');
    expect(fileContent1.tradeHistory[0].closeReasonCode).toBe('FORCED_RESET');

    // Financial fields preserved
    expect(fileContent1.trades[0].pnl).toBe(50);

    // Second run with apply (idempotency check)
    const res2 = runTradeMigration({ dbPath: tempDbPath, apply: true });
    expect(res2.alreadyValidCount).toBe(3);
    expect(res2.migratedTradesCount).toBe(0);
  });
});
